#!/usr/bin/env python3
"""
StrideSense - Model C-Header Exporter
Transpiles trained scikit-learn models (DecisionTree / RandomForest) into pure,
zero-dependency, ultra-fast C/C++ code executable on an ESP32 microcontroller.
"""

import os
from sklearn.tree import _tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

CLASS_NAMES = ["Standing", "Walking", "Running", "Sitting", "Fall"]

def tree_to_c_code(tree, feature_names, indent="    "):
    """Recursively converts a scikit-learn DecisionTreeClassifier into nested C if-else blocks."""
    tree_ = tree.tree_
    feature_name = [
        feature_names[i] if i != _tree.TREE_UNDEFINED else "undefined!"
        for i in tree_.feature
    ]

    lines = []

    def recurse(node, depth):
        ind = indent * depth
        if tree_.feature[node] != _tree.TREE_UNDEFINED:
            name = feature_name[node]
            feat_idx = tree_.feature[node]
            threshold = tree_.threshold[node]
            lines.append(f"{ind}if (features[{feat_idx}] <= {threshold:.5f}f) {{ // {name}")
            recurse(tree_.children_left[node], depth + 1)
            lines.append(f"{ind}}} else {{")
            recurse(tree_.children_right[node], depth + 1)
            lines.append(f"{ind}}}")
        else:
            # Leaf node: get class with highest value
            values = tree_.value[node][0]
            class_idx = int(values.argmax())
            lines.append(f"{ind}return {class_idx}; // {CLASS_NAMES[class_idx]}")

    recurse(0, 1)
    return "\n".join(lines)

def export_random_forest_to_c(rf_model: RandomForestClassifier, feature_names, output_header_path: str):
    """
    Exports a lightweight Random Forest or single pruned Decision Tree to a C header file.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_header_path)), exist_ok=True)

    n_estimators = len(rf_model.estimators_)

    tree_functions = []
    for i, estimator in enumerate(rf_model.estimators_):
        func_body = tree_to_c_code(estimator, feature_names, indent="    ")
        tree_functions.append(f"""
static inline int evaluate_tree_{i}(const float* features) {{
{func_body}
}}
""")

    trees_c = "\n".join(tree_functions)

    header_content = f"""/*
 * StrideSense - Edge TinyML Model Header
 * Auto-generated by export_c_model.py
 * Pure C/C++ implementation for ESP32 with zero external dependencies.
 */

#ifndef STRIDESENSE_MODEL_DATA_H
#define STRIDESENSE_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {{
#endif

// Activity Class Definitions
typedef enum {{
    ACTIVITY_STANDING = 0,
    ACTIVITY_WALKING  = 1,
    ACTIVITY_RUNNING  = 2,
    ACTIVITY_SITTING  = 3,
    ACTIVITY_FALL     = 4
}} ActivityClass;

static const char* const ACTIVITY_NAMES[] = {{
    "Standing",
    "Walking",
    "Running",
    "Sitting",
    "Fall"
}};

#define STRIDESENSE_NUM_FEATURES {len(feature_names)}
#define STRIDESENSE_NUM_CLASSES  {len(CLASS_NAMES)}
#define STRIDESENSE_NUM_TREES    {n_estimators}

{trees_c}

/**
 * Predicts activity class using ensemble majority voting across decision trees.
 * @param features Pointer to an array of {len(feature_names)} float features.
 * @param out_confidence Pointer to receive the voting confidence (0.0 to 1.0), or NULL.
 * @return Predicted ActivityClass
 */
static inline ActivityClass predict_activity(const float* features, float* out_confidence) {{
    int votes[STRIDESENSE_NUM_CLASSES] = {{0}};

"""

    for i in range(n_estimators):
        header_content += f"    votes[evaluate_tree_{i}(features)]++;\n"

    header_content += f"""
    int max_votes = -1;
    int best_class = 0;
    for (int c = 0; c < STRIDESENSE_NUM_CLASSES; c++) {{
        if (votes[c] > max_votes) {{
            max_votes = votes[c];
            best_class = c;
        }}
    }}

    if (out_confidence != 0) {{
        *out_confidence = (float)max_votes / (float)STRIDESENSE_NUM_TREES;
    }}

    return (ActivityClass)best_class;
}}

#ifdef __cplusplus
}}
#endif

#endif // STRIDESENSE_MODEL_DATA_H
"""

    with open(output_header_path, "w") as f:
        f.write(header_content)

    print(f" C Header successfully exported to: {output_header_path}")
