/*
 * StrideSense - Edge TinyML Model Header
 * Auto-generated by export_c_model.py
 * Pure C/C++ implementation for ESP32 with zero external dependencies.
 */

#ifndef STRIDESENSE_MODEL_DATA_H
#define STRIDESENSE_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

// Activity Class Definitions
typedef enum {
    ACTIVITY_STANDING = 0,
    ACTIVITY_WALKING  = 1,
    ACTIVITY_RUNNING  = 2,
    ACTIVITY_SITTING  = 3,
    ACTIVITY_FALL     = 4
} ActivityClass;

static const char* const ACTIVITY_NAMES[] = {
    "Standing",
    "Walking",
    "Running",
    "Sitting",
    "Fall"
};

#define STRIDESENSE_NUM_FEATURES 24
#define STRIDESENSE_NUM_CLASSES  5
#define STRIDESENSE_NUM_TREES    7


static inline int evaluate_tree_0(const float* features) {
    if (features[22] <= 488.55998f) { // heel_force_mean
        if (features[15] <= 192.05500f) { // svm_gyro_mean
            if (features[13] <= 1.39674f) { // svm_acc_max
                if (features[0] <= 0.44825f) { // acc_x_mean
                    return 3; // Sitting
                } else {
                    return 4; // Fall
                }
            } else {
                return 1; // Walking
            }
        } else {
            return 2; // Running
        }
    } else {
        if (features[3] <= 0.31520f) { // acc_y_std
            if (features[23] <= 824.17001f) { // forefoot_force_mean
                if (features[9] <= 1.10561f) { // gyro_y_std
                    return 4; // Fall
                } else {
                    return 0; // Standing
                }
            } else {
                if (features[21] <= 0.91417f) { // medial_lateral_ratio
                    if (features[11] <= 0.81105f) { // gyro_z_std
                        return 0; // Standing
                    } else {
                        if (features[21] <= 0.89883f) { // medial_lateral_ratio
                            return 0; // Standing
                        } else {
                            return 4; // Fall
                        }
                    }
                } else {
                    return 0; // Standing
                }
            }
        } else {
            return 4; // Fall
        }
    }
}


static inline int evaluate_tree_1(const float* features) {
    if (features[11] <= 45.51701f) { // gyro_z_std
        if (features[9] <= 109.86705f) { // gyro_y_std
            if (features[22] <= 215.68000f) { // heel_force_mean
                return 3; // Sitting
            } else {
                if (features[9] <= 1.06409f) { // gyro_y_std
                    if (features[13] <= 1.12775f) { // svm_acc_max
                        if (features[21] <= 0.90419f) { // medial_lateral_ratio
                            return 4; // Fall
                        } else {
                            return 4; // Fall
                        }
                    } else {
                        return 0; // Standing
                    }
                } else {
                    if (features[3] <= 0.07799f) { // acc_y_std
                        return 0; // Standing
                    } else {
                        return 4; // Fall
                    }
                }
            }
        } else {
            return 1; // Walking
        }
    } else {
        return 2; // Running
    }
}


static inline int evaluate_tree_2(const float* features) {
    if (features[11] <= 45.57764f) { // gyro_z_std
        if (features[11] <= 13.52843f) { // gyro_z_std
            if (features[17] <= 1214.92001f) { // force_total_mean
                return 3; // Sitting
            } else {
                if (features[21] <= 0.75953f) { // medial_lateral_ratio
                    return 4; // Fall
                } else {
                    if (features[3] <= 0.03425f) { // acc_y_std
                        if (features[15] <= 1.57755f) { // svm_gyro_mean
                            return 0; // Standing
                        } else {
                            return 0; // Standing
                        }
                    } else {
                        if (features[9] <= 1.02940f) { // gyro_y_std
                            return 4; // Fall
                        } else {
                            return 0; // Standing
                        }
                    }
                }
            }
        } else {
            return 1; // Walking
        }
    } else {
        return 2; // Running
    }
}


static inline int evaluate_tree_3(const float* features) {
    if (features[3] <= 0.23784f) { // acc_y_std
        if (features[19] <= 1413.00000f) { // force_total_max
            return 3; // Sitting
        } else {
            if (features[17] <= 2378.83997f) { // force_total_mean
                return 4; // Fall
            } else {
                if (features[2] <= 0.02992f) { // acc_y_mean
                    if (features[9] <= 0.99065f) { // gyro_y_std
                        if (features[20] <= 0.95716f) { // heel_forefoot_ratio
                            return 0; // Standing
                        } else {
                            return 4; // Fall
                        }
                    } else {
                        return 0; // Standing
                    }
                } else {
                    return 4; // Fall
                }
            }
        }
    } else {
        if (features[19] <= 6586.00000f) { // force_total_max
            return 1; // Walking
        } else {
            if (features[19] <= 9780.00000f) { // force_total_max
                return 2; // Running
            } else {
                return 4; // Fall
            }
        }
    }
}


static inline int evaluate_tree_4(const float* features) {
    if (features[17] <= 1940.48999f) { // force_total_mean
        if (features[11] <= 45.51701f) { // gyro_z_std
            if (features[15] <= 57.47792f) { // svm_gyro_mean
                return 3; // Sitting
            } else {
                return 1; // Walking
            }
        } else {
            return 2; // Running
        }
    } else {
        if (features[12] <= 1.46021f) { // svm_acc_mean
            if (features[21] <= 0.75840f) { // medial_lateral_ratio
                return 4; // Fall
            } else {
                if (features[14] <= 0.04350f) { // svm_acc_std
                    if (features[6] <= 0.07460f) { // gyro_x_mean
                        return 0; // Standing
                    } else {
                        if (features[20] <= 1.07184f) { // heel_forefoot_ratio
                            return 0; // Standing
                        } else {
                            return 4; // Fall
                        }
                    }
                } else {
                    return 4; // Fall
                }
            }
        } else {
            return 2; // Running
        }
    }
}


static inline int evaluate_tree_5(const float* features) {
    if (features[13] <= 1.43423f) { // svm_acc_max
        if (features[9] <= 1.06409f) { // gyro_y_std
            if (features[19] <= 1435.00000f) { // force_total_max
                return 3; // Sitting
            } else {
                if (features[5] <= 0.04019f) { // acc_z_std
                    return 4; // Fall
                } else {
                    return 0; // Standing
                }
            }
        } else {
            if (features[14] <= 0.04839f) { // svm_acc_std
                return 0; // Standing
            } else {
                return 4; // Fall
            }
        }
    } else {
        if (features[19] <= 6586.50000f) { // force_total_max
            return 1; // Walking
        } else {
            if (features[12] <= 1.44588f) { // svm_acc_mean
                return 4; // Fall
            } else {
                return 2; // Running
            }
        }
    }
}


static inline int evaluate_tree_6(const float* features) {
    if (features[19] <= 3641.00000f) { // force_total_max
        if (features[23] <= 541.51001f) { // forefoot_force_mean
            return 3; // Sitting
        } else {
            if (features[9] <= 0.94684f) { // gyro_y_std
                return 4; // Fall
            } else {
                if (features[12] <= 0.99252f) { // svm_acc_mean
                    if (features[20] <= 1.30639f) { // heel_forefoot_ratio
                        return 4; // Fall
                    } else {
                        return 0; // Standing
                    }
                } else {
                    if (features[23] <= 1020.81000f) { // forefoot_force_mean
                        if (features[14] <= 0.04337f) { // svm_acc_std
                            return 0; // Standing
                        } else {
                            return 4; // Fall
                        }
                    } else {
                        return 0; // Standing
                    }
                }
            }
        }
    } else {
        if (features[3] <= 0.51960f) { // acc_y_std
            return 1; // Walking
        } else {
            if (features[11] <= 30.23428f) { // gyro_z_std
                return 4; // Fall
            } else {
                return 2; // Running
            }
        }
    }
}


/**
 * Predicts activity class using ensemble majority voting across decision trees.
 * @param features Pointer to an array of 24 float features.
 * @param out_confidence Pointer to receive the voting confidence (0.0 to 1.0), or NULL.
 * @return Predicted ActivityClass
 */
static inline ActivityClass predict_activity(const float* features, float* out_confidence) {
    int votes[STRIDESENSE_NUM_CLASSES] = {0};

    votes[evaluate_tree_0(features)]++;
    votes[evaluate_tree_1(features)]++;
    votes[evaluate_tree_2(features)]++;
    votes[evaluate_tree_3(features)]++;
    votes[evaluate_tree_4(features)]++;
    votes[evaluate_tree_5(features)]++;
    votes[evaluate_tree_6(features)]++;

    int max_votes = -1;
    int best_class = 0;
    for (int c = 0; c < STRIDESENSE_NUM_CLASSES; c++) {
        if (votes[c] > max_votes) {
            max_votes = votes[c];
            best_class = c;
        }
    }

    if (out_confidence != 0) {
        *out_confidence = (float)max_votes / (float)STRIDESENSE_NUM_TREES;
    }

    return (ActivityClass)best_class;
}

#ifdef __cplusplus
}
#endif

#endif // STRIDESENSE_MODEL_DATA_H
